project_id = "qfavfwvsficnqaznincz"

[functions.news-ai]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.noticias-ai-generate]
verify_jwt = false

[functions.reporter-batch]
verify_jwt = false

[functions.rss-parser]
verify_jwt = false
